#   gem install fb
#   gem 'fb'
development:
  adapter: fb
  database: 172.16.11.55/3050:mypepsdev
  username: SYSDBA
  password: masterkey
  downcase_names: true

production:
  adapter: fb
  database: 172.16.11.55/3050:mypepsdev
  username: SYSDBA
  password: masterkey
  downcase_names: true